name: Lint Markdown

on:
  pull_request:
    paths:
      - '**/*.md'
  push:
    branches:
      - main

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Lint Markdown files
        run: markdownlint . --config .markdownlint.json
        continue-on-error: true 

      - name: Summary
        if: always()
        run: echo "✅ Markdown lint completed"
